asssemble modified2

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -4,6 +4,15 @@
 
 echo "Making pre-invocation changes..."
 /usr/libexec/s2i/assemble
+rc=$?
+
+if [ $rc -eq 0 ]; then
+    echo "After successful assembling"
+else
+    echo "After failed assembling"
+fi
+
+exit $rc
 
 if [ -f ./lib/native/libsapjco3.so ]; then
   echo "---> Copying libsapjco3 library..."
